name: Notify PR opened
on:
  pull_request:
    types: [opened]
jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: PR Details
      run: |
          echo "PR id : ${{ github.event.pull_request.id }}"
          echo "PR node_id : ${{ github.event.pull_request.node_id }}"
          echo "PR html_url : ${{ github.event.pull_request.html_url }}"
          echo "PR title : ${{ github.event.pull_request.title }}"
          echo "PR user name : ${{ github.event.pull_request.user.name }}"
          echo "PR base label : ${{ github.event.pull_request.base.label }}"
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '
            {
              "cardsV2": [
                {
                  "cardId": "${{ github.event.pull_request.node_id }}",
                  "card": {
                    "header": {
                      "title": "Novo Pull Request - ${{ github.event.pull_request.base.label }}",
                      "subtitle": "${{ github.event.pull_request.title }}",
                      "imageUrl": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",

                    },
                    "sections": [
                      {
                        "collapsible": false,
                        "uncollapsibleWidgetsCount": 0,
                        "widgets": [
                          {
                            "decoratedText": {
                              "topLabel": "Título",
                              "text": "${{ github.event.pull_request.title }}"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "PERSON"
                              },
                              "topLabel": "Autor",
                              "text": "${{ github.event.pull_request.user.name }}"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "BOOKMARK"
                              },
                              "topLabel": "Branch alvo",
                              "text": "${{ github.event.pull_request.base.label }}"
                            }
                          },
                          {
                            "buttonList": {
                              "buttons": [
                                {
                                  "text": "Abrir no GitHub",
                                  "onClick": {
                                    "openLink": {
                                      "url": "${{ github.event.pull_request.html_url }}"
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
          '