name: Notify PR merged
on:
  pull_request:
    types: [closed]
jobs:
  notify-on-google-chat-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request PATCH 'https://chat.googleapis.com/v1/spaces/${{ secrets.GOOGLE_CHAT_SPACE }}/messages/client-${{ github.event.repository.name }}-${{ github.event.pull_request.number }}?key=${{ secrets.GOOGLE_CHAT_KEY }}&token=${{ secrets.GOOGLE_CHAT_TOKEN }}&updateMask=cardsV2' \
          --header 'Content-Type: application/json' \
          --data-raw '
            {
              "thread": {
                "threadKey": "${{ github.event.pull_request.node_id }}"
              },
              "cardsV2": [
                {
                  "cardId": "${{ github.event.pull_request.node_id }}",
                  "card": {
                    "header": {
                      "title": "Pull Request Mergeado - ${{ github.event.pull_request.base.label }}",
                      "subtitle": "${{ github.event.pull_request.title }}",
                      "imageUrl": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",

                    },
                    "sections": [
                      {
                        "collapsible": false,
                        "uncollapsibleWidgetsCount": 0,
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "<b><font color=\"#FF0000\">MERGEADO!</font></b>"
                            }
                          },
                          {
                            "decoratedText": {
                              "topLabel": "Título",
                              "text": "<s>${{ github.event.pull_request.title }}</s>"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "PERSON"
                              },
                              "topLabel": "Autor",
                              "text": "<s>${{ github.event.pull_request.user.login }}</s>"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "BOOKMARK"
                              },
                              "topLabel": "Branch alvo",
                              "text": "<s>${{ github.event.pull_request.base.label }}</s>"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "DESCRIPTION"
                              },
                              "topLabel": "Link para o GitHub",
                              "text": "<a href=\"${{ github.event.pull_request.html_url }}\">${{ github.event.pull_request.html_url }}</a>"
                            }
                          },
                          {
                            "buttonList": {
                              "buttons": [
                                {
                                  "text": "Abrir no GitHub",
                                  "onClick": {
                                    "openLink": {
                                      "url": "${{ github.event.pull_request.html_url }}"
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
          '