name: Notify PR opened
on:
  pull_request:
    types: [opened]
jobs:
  notify-on-google-chat:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}&messageReplyOption=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD' \
          --header 'Content-Type: application/json' \
          --data-raw '
            {
              "thread": {
                "threadKey": "${{ github.event.pull_request.node_id }}"
              },
              "cardsV2": [
                {
                  "cardId": "${{ github.event.pull_request.node_id }}",
                  "card": {
                    "header": {
                      "title": "Novo Pull Request - ${{ github.event.repository.name }}",
                      "subtitle": "${{ github.event.pull_request.base.label }}",
                      "imageUrl": "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",

                    },
                    "sections": [
                      {
                        "collapsible": false,
                        "uncollapsibleWidgetsCount": 1,
                        "widgets": [
                          {
                            "decoratedText": {
                              "topLabel": "Título",
                              "text": "${{ github.event.pull_request.title }}"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "PERSON"
                              },
                              "topLabel": "Autor",
                              "text": "${{ github.event.pull_request.user.login }}"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "BOOKMARK"
                              },
                              "topLabel": "Branch alvo",
                              "text": "${{ github.event.pull_request.base.label }}"
                            }
                          },
                          {
                            "decoratedText": {
                              "startIcon": {
                                "knownIcon": "DESCRIPTION"
                              },
                              "topLabel": "Link para o GitHub",
                              "text": "<a href=\"${{ github.event.pull_request.html_url }}\">${{ github.event.pull_request.html_url }}</a>"
                            }
                          },
                          {
                            "buttonList": {
                              "buttons": [
                                {
                                  "text": "Abrir no GitHub",
                                  "onClick": {
                                    "openLink": {
                                      "url": "${{ github.event.pull_request.html_url }}"
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
          '