name: Notify PR review
on:
  pull_request_review:
    types: [submitted]
jobs:
  notify-on-google-chat-approved:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}&messageReplyOption=REPLY_MESSAGE_OR_FAIL' \
          --header 'Content-Type: application/json' \
          --data-raw '
            {
              "thread": {
                "threadKey": "${{ github.event.pull_request.node_id }}"
              },
              "cardsV2": [
                {
                  "cardId": "${{ github.event.review.node_id }}",
                  "card": {
                    "header": {
                      "title": "Pull Request APROVADO!",
                      "subtitle": "Revisado por ${{ github.event.review.user.login }}",
                      "imageUrl": "https://cdn-icons-png.flaticon.com/512/3472/3472620.png"
                    },
                    "sections": [
                      {
                        "collapsible": true,
                        "uncollapsibleWidgetsCount": 0,
                        "widgets": [
                          {
                            "image": {
                                "imageUrl": "https://camo.githubusercontent.com/2b6bc82ca348cb81e1cef9a2262f08c6d534d11b630c8d2729a2d7a315cd812d/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966"
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
          '

  notify-on-google-chat-commented:
    if: github.event.review.state == 'commented'
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}&messageReplyOption=REPLY_MESSAGE_OR_FAIL' \
          --header 'Content-Type: application/json' \
          --data-raw '
            {
              "thread": {
                "threadKey": "${{ github.event.pull_request.node_id }}"
              },
              "cardsV2": [
                {
                  "cardId": "${{ github.event.review.node_id }}",
                  "card": {
                    "header": {
                      "title": "Novo comentário no PR",
                      "subtitle": "Revisado por ${{ github.event.review.user.login }}",
                      "imageUrl": "https://www.intelligentvc.co.uk/wp-content/uploads/2015/11/animat-chat-color.gif"
                    }
                  }
                }
              ]
            }
          '

  notify-on-google-chat-changes-requested:
    if: github.event.review.state == 'changes_requested'
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}&messageReplyOption=REPLY_MESSAGE_OR_FAIL' \
          --header 'Content-Type: application/json' \
          --data-raw '
            {
              "thread": {
                "threadKey": "${{ github.event.pull_request.node_id }}"
              },
              "cardsV2": [
                {
                  "cardId": "${{ github.event.review.node_id }}",
                  "card": {
                    "header": {
                      "title": "Mudanças solicitadas no PR",
                      "subtitle": "Revisado por ${{ github.event.review.user.login }}",
                      "imageUrl": "https://fonts.gstatic.com/s/e/notoemoji/15.0/1f6a8/512.png"
                    }
                  }
                }
              ]
            }
          '