name: Notify PR opened
on:
  pull_request_review:
    types: [submitted]
jobs:
  notify-on-google-chat-approved:
    if: github.event.review.state == 'APPROVED'
    runs-on: ubuntu-latest
    steps:
    - name: PR Review Details
      run: |
          echo "PR id : ${{ github.event.pull_request.id }}"
          echo "PR node_id : ${{ github.event.pull_request.node_id }}"
          echo "PR html_url : ${{ github.event.pull_request.html_url }}"
          echo "PR title : ${{ github.event.pull_request.title }}"
          echo "PR user login: ${{ github.event.pull_request.user.login }}"
          echo "PR base label : ${{ github.event.pull_request.base.label }}"
          echo "------------------------------------"
          echo "REVIEW id : ${{ github.event.review.node_id }}"
          echo "REVIEW node_id : ${{ github.event.review.node_id }}"
          echo "REVIEW state : ${{ github.event.review.state }}"
          echo "REVIEW user login : ${{ github.event.review.user.login }}"
    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.GOOGLE_CHAT_WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '
            {
              "cardsV2": [
                {
                  "cardId": "${{ github.event.pull_request.node_id }}",
                  "card": {
                  "header": {
                    "title": "Pull Request Revisado - Aprovado",
                    "imageUrl": "https://cdn-icons-png.flaticon.com/512/3472/3472620.png"
                  },
                  "sections": [
                    {
                      "collapsible": true,
                      "uncollapsibleWidgetsCount": 0,
                      "widgets": [
                        {
                          "decoratedText": {
                            "topLabel": "Revisado por",
                            "text": "${{ github.event.review.user.login }}"
                          }
                        },
                        {
                          "image": {
                              "imageUrl": "https://camo.githubusercontent.com/2b6bc82ca348cb81e1cef9a2262f08c6d534d11b630c8d2729a2d7a315cd812d/68747470733a2f2f6d65646961342e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966"
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          '